# version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres       
      POSTGRES_PASSWORD: postgres   
      POSTGRES_DB: povepo            
    ports:
      - "5432:5432"                 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - work

  audio_povepo:
    build:
      context: ./
    container_name: audio_povepo
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    env_file:
      - ./.env
    networks:
      - work


networks:
  work:
    driver: bridge

volumes:
  postgres_data: