"""create audio table

Revision ID: b8f27f84dc23
Revises: 9746643fe1c3
Create Date: 2025-04-03 02:05:57.650307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8f27f84dc23'
down_revision: Union[str, None] = '9746643fe1c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audios_info',
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('filename')
    )
    op.create_index(op.f('ix_audios_info_filename'), 'audios_info', ['filename'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audios_info_filename'), table_name='audios_info')
    op.drop_table('audios_info')
    # ### end Alembic commands ###
